module.exports = {
  projects: [
    '<rootDir>/apps/russian/cabinet',
    '<rootDir>/libs/russian/ui/styles',
    '<rootDir>/libs/russian/ui/layout',
    '<rootDir>/libs/russian/ui/container',
    '<rootDir>/libs/russian/content/home/page',
    '<rootDir>/libs/russian/errors/not-found/page',
    '<rootDir>/libs/russian/errors/shared',
    '<rootDir>/libs/russian/errors/server-error/page',
    '<rootDir>/libs/russian/errors/permission-denied/page',
    '<rootDir>/libs/core/storage/common',
    '<rootDir>/libs/core/storage/memory',
    '<rootDir>/libs/core/storage/local',
    '<rootDir>/libs/core/storage/session',
    '<rootDir>/libs/core/cookie/service',
    '<rootDir>/libs/core/environments/service',
    '<rootDir>/libs/core/config/service',
    '<rootDir>/libs/core/api/service',
    '<rootDir>/libs/core/api/interceptors/content-type',
    '<rootDir>/libs/core/api/interceptors/with-credentials',
    '<rootDir>/libs/core/store/root',
    '<rootDir>/libs/core/store/utils',
    '<rootDir>/libs/core/store/watcher',
    '<rootDir>/libs/russian/ui/grid',
    '<rootDir>/libs/core/platform/service',
  ],
};
