### Save empty
POST http://localhost:3000/trackers/records
Content-Type: application/json
Accept: application/json

{
  "records": [],
  "visitor": "12345678"
}

### Save records
POST http://localhost:3000/trackers/records
Content-Type: application/json
Accept: application/json

{
  "records": [
    {
      "type": "focus",
      "element": "window",
      "uid": "1234",
      "time": 12345,
      "data": {},
      "url": "/",
      "keys": "",
      "value": ""
    }
  ],
  "visitor": "12345678"
}
